name: default
channels:
  - conda-forge
dependencies:
  - python==3.7.9
  - numpy
  - matplotlib
  - tensorflow==2.3.0
  - tensorboard
  - torch
  - setuptools
  - Pillow
  - h5py
  - arrow
  - Keras
  - pydot
